### ISSUE TITLE
Complete error messages not shown

### ISSUE THREAD

**Issue by 5outh** [SublimeLinter/SublimeLinter-hlint#1]
When running hlint from the command line on a test file, I get the error:

```
Error: Eta reduce
Found:
  testing a b c = f a b c
Why not:
  testing = f

1 suggestion
```

But while running a report through the plugin (or viewing the error on the sidebar), I only get the top line:

```
  hlint:
    141: Eta reduce
```

The suggestions are the best part of hlint; would it be possible to include the full text somehow, via a command?

**Comment by kaste** [comment]
Done by using the JSON mode
